### ISSUE TITLE
Passing of the torch.

### ISSUE THREAD

**Issue by saildot4k** [saildot4k/MSS54-XDFs#12]
Alright guys, I just sold my E30 S54 build on BaT a couple weeks ago, and need to pass the torch as I will have no further way to test, and now a passing interest as I drive slower cars that can go over pebbles.

Please, share thoughts who would be best for this. My goal was to continue the help and mission of continuing this "the open xdf project". 

So I would like to transfer ownership to someone knowledable enough to keep this organized, add and not take advantage of others. I have no problem with others using this to create more software and profit from this, but this, the xdfs, and the swap info should remain free and open, and allow collaborators to join (but please keep a backup should it get toyed with) The orig info is in a different branch that should be locked. Any takers?

**Comment by ChrisDeBmw** [comment]
Oh, it's a pity you stop! You've done great so far and always shown great interest.
I would nonetheless suggest that @terraphantm take the torch.

**Comment by saildot4k** [comment]
@terraphantm Thoughts? You want to be the new "owner" of this repository?
