### ISSUE TITLE
M3forum.net DNS issues

### ISSUE THREAD

**Issue by eacmen** [saildot4k/MSS54-XDFs#16]
@exodus454 @terraphantm @saildot4k @Prepare2GetRekt 

This is totally unrelated to this repo but is anyone else having issues resolving the m3forum.net domain? Anything I can do to help?

**Comment by terraphantm** [comment]
Yeah it's sort of in limbo. I don't have access to any of the actual host stuff. Ian (obioban) got in touch with the guy who was doing most of the admining, and he's trying to get in touch with the actual site owner of the site

**Comment by eacmen** [comment]
Thanks @terraphantm  just wanted to make sure it wasn’t just me.
