### ISSUE TITLE
XDF XXXX: Parameter Offset Incorrect

### ISSUE THREAD

**Issue by chrisseiner** [saildot4k/MSS54-XDFs#7]
**XDF Version**
XDF hw2101_V4

**Parameter to Correct ie K_LA_FMIN**
Paramter: KF_SMG_N_ZIEL_OFF_K / KF_SMG_N_ZIEL_OFF_S

**Parameter Type: Delete those that do not apply**

Table

**XML Data to replace in source**
The Values Show "100 - "set value"
Like: writing 100 is being interpreted as 0.0 or 80 being shown as 20.0

**Comment by saildot4k** [comment]
Can you please describe the problem further? What are you expecting? The cell conversion is (x/128)*100 according to the A2L.

Maybe attach what you are seeing vs what you expect?

**Comment by chrisseiner** [comment]
In those tables you u insert values to modify the the automated revving on downshift.
From my understanding those values range from 0 to 100 (0 being no rev match and 100 being a lot of rev). But in this XDF (I think it's in all of them) if you want 100 you have to write 0.
Or if you want 20 you have to write 80.
I hope things got a bit clearer. I can add some pictures later

BTW: If anyone from the m3forum.net reads this: I cannot post or comment there for unknown reasons.
I made some tuning and burble and pop maps for SMG M3s that work and don't fuck with your smg car performance...

**Comment by saildot4k** [comment]
Please, provide pics/video. I am still not understanding. Sometimes TunerPro has bugs, but I just checked and I can alter the table as desired without the values changing intermittently or flipping.

**Comment by chrisseiner** [comment]
![smg problems](https://user-images.githubusercontent.com/53100692/62191902-d608f400-b374-11e9-9a86-c6fa2badbfc3.PNG)

All values in this table are shown as "distance to 100 values"
 
You see those "0.0 values? They should be "100.0"
Or 20.3 should 79.7

I hope you understand now.

**Comment by saildot4k** [comment]
Not seeing that at all. Maybe your master/slave is opposite this standard? Upload your partial bin.

This is what I have in 2101, 2501, and 2801. Stopped checking after that..
<img width="549" alt="Screen Shot 2019-07-31 at 12 30 48 AM" src="https://user-images.githubusercontent.com/45891275/62192506-99180f80-b32a-11e9-8301-11b4746d63ac.png">

**Comment by chrisseiner** [comment]
[test_3007.pdf](https://github.com/saildot4k/MSS54-XDFs/files/3450433/test_3007.pdf)


rename to .bin to make it work.

**Comment by chrisseiner** [comment]
> Not seeing that at all. Maybe your master/slave is opposite this standard? Upload your partial bin.
> 
> This is what I have in 2101, 2501, and 2801. Stopped checking after that..
> <img alt="Screen Shot 2019-07-31 at 12 30 48 AM" width="549" src="https://user-images.githubusercontent.com/45891275/62192506-99180f80-b32a-11e9-8301-11b4746d63ac.png">

See: those are wrong:

Equotion should be: 100-((x/128)*100)

Your map implied there is 100% rev match at 1000 RPM (this is definetly not happening with those settings). There is ZERO Rev Match at 1000 RPM.

**Comment by saildot4k** [comment]
Check it out with your equation: 100-((x/128)*100)
<img width="553" alt="Screen Shot 2019-07-31 at 8 25 19 AM" src="https://user-images.githubusercontent.com/45891275/62225228-e026f480-b36c-11e9-9414-e213a2d46e60.png">

**Comment by chrisseiner** [comment]
> Check it out with your equation: 100-((x/128)*100)
> <img alt="Screen Shot 2019-07-31 at 8 25 19 AM" width="553" src="https://user-images.githubusercontent.com/45891275/62225228-e026f480-b36c-11e9-9414-e213a2d46e60.png">

thats correct for stock m3

**Comment by saildot4k** [comment]
Great. Just curious, as I could not find anyone else talking about these 2 tables, do you have documentation, or other proof that the cell calculation is wrong. I only ask because I know there is a huge amount of misinformation out there, and the plan is to have 2+ eyes helping make sure we change things accordingly. 

Also, the Y values IE 0.0 | -2.0 | -3.0 | -4.0
Is that the correct conversion too. Do you happen to have an english translation for the function? Or possibly the E-Power Framework?

**Comment by chrisseiner** [comment]
I have seen screenshots showing the values in the way I think they should be calculated. Other than that I would argue that at 1000 rpm it makes sense to have 0.0 (No Revmatching) while at higher rpm the value rises and you get rev matching. Compare the csl maps as the stock m3 hardly does any rev matching

Concerning the Y-Values we would have to try decelerating and see the smg reaction to be 100 sure.
But i think they are mostly correct couse after my changes in all fields the SMG behaves exactly
the way I want (perfect auto rev match everywhere)

I can try to translate to english whatever you want as i am native german

**Comment by saildot4k** [comment]
From 52_V508.A2L (MSS52) 
Unable to find function in MSS54 A2L that I have: M3_mss54_Ext_Ram.a2l

Trying to understand this older A2L conversion, to double check. I think it usually best to follow the output of the A2L.


> /begin CHARACTERISTIC  KF_SMG_N_ZIEL_OFF_K                  /* Name */
>     "-"                                           /* Langbezeichner */
>     MAP                                                      /* Typ */
>     0x5F26                                          /* StartAdresse */
>     VALUE_KF_SMG_N_ZIEL_OFF_K                         /* Rec.Layout */
>     100.000000                                          /* MaxDiff. */
>     F00368                                            /* Umrechnung */
>     0.000000                                         /* Untergrenze */
>     100.000000                                        /* Obergrenze */
>   /begin AXIS_DESCR /* ax */                              /* X axis */
>     COM_AXIS                                            /* ...Achse */
>     ax                                           /* EingangsGroesse */
>     F00380                                            /* Umrechnung */
>     4                                              /* Max.Stuetzst. */
>     0.000000                                         /* Untergrenze */
>     -12.000000                                        /* Obergrenze */
>    AXIS_PTS_REF KF_SMG_N_ZIEL_OFF_K_ax_AXIS            /* Datensatz */
>   /end AXIS_DESCR                                     /* end X axis */
>   /begin AXIS_DESCR /* n */                               /* Y axis */
>     COM_AXIS                                            /* ...Achse */
>     n                                            /* EingangsGroesse */
>     F00109                                            /* Umrechnung */
>     6                                              /* Max.Stuetzst. */
>     0.000000                                         /* Untergrenze */
>     10000.000000                                      /* Obergrenze */
>    AXIS_PTS_REF KF_SMG_N_ZIEL_OFF_K_n_AXIS             /* Datensatz */
>   /end AXIS_DESCR                                     /* end Y axis */
>   FUNCTION_LIST  smg                                 /* function(s) */
> /end CHARACTERISTIC                                                  
> 
> /begin RECORD_LAYOUT VALUE_KF_SMG_N_ZIEL_OFF_K                        
>     FNC_VALUES    0 UBYTE ROW_DIR DIRECT                   /* Werte */
> /end RECORD_LAYOUT                                                   
> 
> /begin AXIS_PTS  KF_SMG_N_ZIEL_OFF_K_ax_AXIS          /* PTS X axis */
>     "-"                                           /* Langbezeichner */
>     0x5F1C                                               /* Adresse */
>     ax                                           /* EingangsGroesse */
>     KF_SMG_N_ZIEL_OFF_K_ax_AXIS                       /* Rec.Layout */
>     100.000000                                          /* MaxDiff. */
>     F00380                                            /* Umrechnung */
>     4                                              /* Max.Stuetzst. */
>     0.000000                                         /* Untergrenze */
>     -12.000000                                        /* Obergrenze */
> /end AXIS_PTS                                                        
> 
> /begin RECORD_LAYOUT KF_SMG_N_ZIEL_OFF_K_ax_AXIS                      
>     FIX_NO_AXIS_PTS_X  4                    /* Anzahl Stuetzstellen */
>     AXIS_PTS_X  0 UBYTE INDEX_INCR DIRECT                /* Werte X */
> /end RECORD_LAYOUT                                                    
> 
> /begin AXIS_PTS  KF_SMG_N_ZIEL_OFF_K_n_AXIS          /* PTS Y axis */
>     "-"                                           /* Langbezeichner */
>     0x5F20                                               /* Adresse */
>     n                                            /* EingangsGroesse */
>     KF_SMG_N_ZIEL_OFF_K_n_AXIS                        /* Rec.Layout */
>     100.000000                                          /* MaxDiff. */
>     F00109                                            /* Umrechnung */
>     6                                              /* Max.Stuetzst. */
>     0.000000                                         /* Untergrenze */
>     10000.000000                                      /* Obergrenze */
> /end AXIS_PTS                                                        
> 
> /begin RECORD_LAYOUT KF_SMG_N_ZIEL_OFF_K_n_AXIS                       
>     FIX_NO_AXIS_PTS_Y  6                    /* Anzahl Stuetzstellen */
>     AXIS_PTS_Y  0 UBYTE INDEX_INCR DIRECT                /* Werte Y */
> /end RECORD_LAYOUT                                                    
>  /* -------------------------             ------------------------- */
> 
> /begin CHARACTERISTIC  KF_SMG_N_ZIEL_OFF_S                  /* Name */
>     "-"                                           /* Langbezeichner */
>     MAP                                                      /* Typ */
>     0x5F4A                                          /* StartAdresse */
>     VALUE_KF_SMG_N_ZIEL_OFF_S                         /* Rec.Layout */
>     100.000000                                          /* MaxDiff. */
>     F00368                                            /* Umrechnung */
>     0.000000                                         /* Untergrenze */
>     100.000000                                        /* Obergrenze */
>   /begin AXIS_DESCR /* ax */                              /* X axis */
>     COM_AXIS                                            /* ...Achse */
>     ax                                           /* EingangsGroesse */
>     F00380                                            /* Umrechnung */
>     4                                              /* Max.Stuetzst. */
>     0.000000                                         /* Untergrenze */
>     -12.000000                                        /* Obergrenze */
>    AXIS_PTS_REF KF_SMG_N_ZIEL_OFF_S_ax_AXIS            /* Datensatz */
>   /end AXIS_DESCR                                     /* end X axis */
>   /begin AXIS_DESCR /* n */                               /* Y axis */
>     COM_AXIS                                            /* ...Achse */
>     n                                            /* EingangsGroesse */
>     F00109                                            /* Umrechnung */
>     6                                              /* Max.Stuetzst. */
>     0.000000                                         /* Untergrenze */
>     10000.000000                                      /* Obergrenze */
>    AXIS_PTS_REF KF_SMG_N_ZIEL_OFF_S_n_AXIS             /* Datensatz */
>   /end AXIS_DESCR                                     /* end Y axis */
>   FUNCTION_LIST  smg                                 /* function(s) */
> /end CHARACTERISTIC                                                  
> 
> /begin RECORD_LAYOUT VALUE_KF_SMG_N_ZIEL_OFF_S                        
>     FNC_VALUES    0 UBYTE ROW_DIR DIRECT                   /* Werte */
> /end RECORD_LAYOUT                                                   
> 
> /begin AXIS_PTS  KF_SMG_N_ZIEL_OFF_S_ax_AXIS          /* PTS X axis */
>     "-"                                           /* Langbezeichner */
>     0x5F40                                               /* Adresse */
>     ax                                           /* EingangsGroesse */
>     KF_SMG_N_ZIEL_OFF_S_ax_AXIS                       /* Rec.Layout */
>     100.000000                                          /* MaxDiff. */
>     F00380                                            /* Umrechnung */
>     4                                              /* Max.Stuetzst. */
>     0.000000                                         /* Untergrenze */
>     -12.000000                                        /* Obergrenze */
> /end AXIS_PTS                                                        
> 
> /begin RECORD_LAYOUT KF_SMG_N_ZIEL_OFF_S_ax_AXIS                      
>     FIX_NO_AXIS_PTS_X  4                    /* Anzahl Stuetzstellen */
>     AXIS_PTS_X  0 UBYTE INDEX_INCR DIRECT                /* Werte X */
> /end RECORD_LAYOUT                                                    
> 
> /begin AXIS_PTS  KF_SMG_N_ZIEL_OFF_S_n_AXIS          /* PTS Y axis */
>     "-"                                           /* Langbezeichner */
>     0x5F44                                               /* Adresse */
>     n                                            /* EingangsGroesse */
>     KF_SMG_N_ZIEL_OFF_S_n_AXIS                        /* Rec.Layout */
>     100.000000                                          /* MaxDiff. */
>     F00109                                            /* Umrechnung */
>     6                                              /* Max.Stuetzst. */
>     0.000000                                         /* Untergrenze */
>     10000.000000                                      /* Obergrenze */
> /end AXIS_PTS                                                        
> 
> /begin RECORD_LAYOUT KF_SMG_N_ZIEL_OFF_S_n_AXIS                       
>     FIX_NO_AXIS_PTS_Y  6                    /* Anzahl Stuetzstellen */
>     AXIS_PTS_Y  0 UBYTE INDEX_INCR DIRECT                /* Werte Y */
> /end RECORD_LAYOUT 

                                                                                  `

**Comment by chrisseiner** [comment]
I Can only guess but:
VALUE_KF_SMG_N_ZIEL_OFF_K / Rec.Layout /
100.000000 / MaxDiff. /
F00368 / Umrechnung /
0.000000 / Untergrenze / <--Lower Limit
100.000000 / Obergrenze / <--Upper Limit

So to me those translations suggest that I am right.

Also It makes sense to give u a chance to add rev "unlimited" or till Obergrenze
while it does not make sense to lower a number to zero, excluding negatives, to give you a chance to add rev. 

I hope you can follow me here and that I'm correct

**Comment by saildot4k** [comment]
^Counter, values in xdf with current conversion are already 0≤X≤100. 

Changing the XDF conversion does not change the actual hex values in the tune. It only affords us a way to view the data. IE I could change the PerGear Speed to be viewed in KMH or MPH, but that does not change the actual value.

**Comment by chrisseiner** [comment]
I understand. I know it's doing the right thing but I believe the values to be presentaed with my conversion to be more reasonable for the brain

**Comment by saildot4k** [comment]
If it is doing the right thing, then this is not a bug, feel free to download and modify the conversions as you see fit, but we should retain BMWs conversions.
